In [9]:
import numpy as np
from itertools import combinations

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
x = np.array([[1,2], [4,5]])
y = x @ np.linalg.inv(x.T @ x) @ x.T
x.T

array([[1, 4],
       [2, 5]])

In [12]:
np.amax(np.diagonal(y))

0.9999999999999969

In [13]:
np.sort([2,3,1])

array([1, 2, 3])

In [14]:
np.argmin([4,5,1,7,9,2])

2

In [18]:
a = combinations([1,2,3], 2)
list(a)

[(1, 2), (1, 3), (2, 3)]