In [18]:
import numpy as np
from itertools import combinations
from functools import partial

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
x = np.array([[1,2], [4,5]])
y = x @ np.linalg.inv(x.T @ x) @ x.T
x.T

array([[1, 4],
       [2, 5]])

In [21]:
np.amax(np.diagonal(y))

0.9999999999999969

In [22]:
np.sort([2,3,1])

array([1, 2, 3])

In [23]:
np.argmin([4,5,1,7,9,2])

2

In [76]:
a = combinations(range(4), 2)
for i in a:
    print(i[0])

0
0
0
1
1
2


In [25]:
S = np.array([[1,2,3],[2,3,1],[3,1,2]])
def _wrapper_del(to_delete, s=S):
    return np.delete(s, to_delete, 0)
criterion_func = lambda x: x**2
partial_del = partial(np.delete, arr=S, axis=0)

In [30]:
# function_values = np.empty(3)
# for i in range(3):
#     function_values[i] = criterion_func(np.delete(S, 0, i))

In [31]:
len(list(combinations(range(8), 2))) + len(list(combinations(range(8), 4))) + len(list(combinations(range(8), 6))) + len(list(combinations(range(8), 8)))
2**7

128

In [32]:
# a = combinations([1,2,3, 4], 2)
# for i in list(a):
#     print(S[i,])
# a = combinations([1,2,3, 4], 2)
# list(a)

In [33]:
dim = 9
b = np.where(
    np.arange(dim) % 2 == 0
)[0][1:]
b

array([2, 4, 6, 8], dtype=int64)

In [34]:
p_comps = [2,4, 6, 8]
a = []
# for i in p_comps:
#     a.append(list(combinations(range(10), i)))
# a

In [69]:
S = np.array([[1,2,3],[2,3,1],[3,1,2]])
S[([1],[2]), (0,1)] = S[([2],[1]),(0,1)]
S

array([[1, 2, 3],
       [3, 1, 1],
       [2, 3, 2]])

In [86]:
S = np.array([[1,2,3],[2,3,1],[3,1,2], [4,5,6]])
S_temp = S.copy()
S_temp[[([1],[2])],(0,1)] = S[[([2],[1])],(0,1)]
S_temp

array([[1, 2, 3],
       [3, 1, 1],
       [2, 3, 2],
       [4, 5, 6]])

In [112]:
dim = 10
n_components = np.where(
    np.arange(dim+1) % 2 == 0
)[0][1:]
n_components

array([ 2,  4,  6,  8, 10], dtype=int64)

In [109]:
switching_components_list = []
# loop over even-numbered combinations
for i in n_components:
    switching_components_list.append(list(combinations(range(dim), i)))
switching_components = [item for sublist in switching_components_list for item in sublist]
len(switching_components)

126