In [1]:
import numpy as np
from itertools import combinations
from functools import partial
import pickle
from config import BLD

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
x = np.array([[1,2], [4,5]])
y = x @ np.linalg.inv(x.T @ x) @ x.T
x.T

array([[1, 4],
       [2, 5]])

In [4]:
np.amax(np.diagonal(y))

0.9999999999999969

In [5]:
np.sort([2,3,1])

array([1, 2, 3])

In [6]:
np.argmin([4,5,1,7,9,2])

2

In [81]:
a = combinations(range(4), 2)
list(a)

[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

In [8]:
S = np.array([[1,2,3],[2,3,1],[3,1,2]])
def _wrapper_del(to_delete, s=S):
    return np.delete(s, to_delete, 0)
criterion_func = lambda x: x**2
partial_del = partial(np.delete, arr=S, axis=0)

In [9]:
# function_values = np.empty(3)
# for i in range(3):
#     function_values[i] = criterion_func(np.delete(S, 0, i))

In [10]:
len(list(combinations(range(8), 2))) + len(list(combinations(range(8), 4))) + len(list(combinations(range(8), 6))) + len(list(combinations(range(8), 8)))
2**7

128

In [11]:
# a = combinations([1,2,3, 4], 2)
# for i in list(a):
#     print(S[i,])
# a = combinations([1,2,3, 4], 2)
# list(a)

In [12]:
dim = 9
b = np.where(
    np.arange(dim) % 2 == 0
)[0][1:]
b

array([2, 4, 6, 8], dtype=int64)

In [13]:
p_comps = [2,4, 6, 8]
a = []
# for i in p_comps:
#     a.append(list(combinations(range(10), i)))
# a

In [14]:
S = np.array([[1,2,3],[2,3,1],[3,1,2]])
S[([1],[2]), (0,1)] = S[([2],[1]),(0,1)]
S

array([[1, 2, 3],
       [3, 1, 1],
       [2, 3, 2]])

In [15]:
S = np.array([[1,2,3],[2,3,1],[3,1,2], [4,5,6]])
S_temp = S.copy()
S_temp[[([1],[2])],(0,1)] = S[[([2],[1])],(0,1)]
S_temp

array([[1, 2, 3],
       [3, 1, 1],
       [2, 3, 2],
       [4, 5, 6]])

In [16]:
dim = 10
n_components = np.where(
    np.arange(dim+1) % 2 == 0
)[0][1:]
n_components

array([ 2,  4,  6,  8, 10], dtype=int64)

In [17]:
switching_components_list = []
# loop over even-numbered combinations
for i in n_components:
    switching_components_list.append(list(combinations(range(dim), i)))
switching_components = [item for sublist in switching_components_list for item in sublist]
len(switching_components)

511

In [18]:
type(lambda x: x**2)

function

In [19]:
dict = {"first" : "hallo", "second" : "tschüss"}
for i in dict.keys():
    print(i == "first")
list(dict.keys())

True
False


['first', 'second']

In [20]:
first = BLD / "data" / "full.pickle"
first_sample = pickle.load(open(first, "rb"))

array([[0.375, 0.075],
       [0.125, 0.475],
       [0.175, 0.025],
       [0.425, 0.425],
       [0.325, 0.925],
       [0.975, 0.525],
       [0.925, 0.575],
       [0.525, 0.975],
       [0.775, 0.825],
       [0.475, 0.175],
       [0.825, 0.225],
       [0.075, 0.375],
       [0.275, 0.325],
       [0.625, 0.675],
       [0.025, 0.275],
       [0.225, 0.125],
       [0.675, 0.725],
       [0.875, 0.875],
       [0.725, 0.775],
       [0.575, 0.625]])

In [39]:
target_n_points = 11
3 * target_n_points // 5
dumlist = [1,2,3,4,5,6,7,8]
sublist = [1,6,8]
list(set(dumlist) - set(sublist))

[2, 3, 4, 5, 7]

In [185]:
arr = np.array([(1,2), (3,4), (5,6)])
arr
rows = np.random.default_rng().choice(
    a=arr,
    size=2,
    replace=False,
    axis=0,
    shuffle=False
)
rows

array([[3, 4],
       [5, 6]])

In [168]:
comb = combinations(range(5), 2)
arr = np.array(list(comb))
np.random.default_rng().choice(len(arr)), len(arr)

(2, 10)