In [133]:
import numpy as np
from itertools import combinations

In [134]:
dim = 4

### Old Implementation about even-numbered combinations

In [135]:
n_components = np.where(np.arange(dim + 1) % 2 == 0)[0][1:]
n_components

array([2, 4], dtype=int64)

In [136]:
switching_components_lists = [
        list(combinations(range(dim), i)) for i in n_components
    ]
switching_components_lists

[[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)], [(0, 1, 2, 3)]]

### New implementation

In [137]:
# Create list of number of columns to change. Leave out the case of changing all columns
cols_to_consider = np.arange(dim)

In [138]:
# Create dictionary of possible switches
switching_components_dict_of_sets = {
        f"Consider {i} design variables" : set(combinations(range(dim), i)) for i in cols_to_consider
}
# Delete case of switching nothing
del switching_components_dict_of_sets[f"Consider {cols_to_consider[0]} design variables"]
# Delete last case, because it is only the complement of either the changing one
# (if even dim) or changing two (if uneven dim) variables
del switching_components_dict_of_sets[f"Consider {cols_to_consider[-1]} design variables"]
switching_components_dict_of_sets

{'Consider 1 design variables': {(0,), (1,), (2,), (3,)},
 'Consider 2 design variables': {(0, 1),
  (0, 2),
  (0, 3),
  (1, 2),
  (1, 3),
  (2, 3)}}

In [139]:

n_components = np.where(help % 2 == 0)[0][1:]
n_components

array([2], dtype=int64)

In [140]:
np.where(help % 2 == 0)[0]

array([0, 2], dtype=int64)